require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WookiesController do

  # This should return the minimal set of attributes required to create a valid
  # Wookie. As you add validations to Wookie, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WookiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wookies as @wookies" do
      wookie = Wookie.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wookies).should eq([wookie])
    end
  end

  describe "GET show" do
    it "assigns the requested wookie as @wookie" do
      wookie = Wookie.create! valid_attributes
      get :show, {:id => wookie.to_param}, valid_session
      assigns(:wookie).should eq(wookie)
    end
  end

  describe "GET new" do
    it "assigns a new wookie as @wookie" do
      get :new, {}, valid_session
      assigns(:wookie).should be_a_new(Wookie)
    end
  end

  describe "GET edit" do
    it "assigns the requested wookie as @wookie" do
      wookie = Wookie.create! valid_attributes
      get :edit, {:id => wookie.to_param}, valid_session
      assigns(:wookie).should eq(wookie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Wookie" do
        expect {
          post :create, {:wookie => valid_attributes}, valid_session
        }.to change(Wookie, :count).by(1)
      end

      it "assigns a newly created wookie as @wookie" do
        post :create, {:wookie => valid_attributes}, valid_session
        assigns(:wookie).should be_a(Wookie)
        assigns(:wookie).should be_persisted
      end

      it "redirects to the created wookie" do
        post :create, {:wookie => valid_attributes}, valid_session
        response.should redirect_to(Wookie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wookie as @wookie" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wookie.any_instance.stub(:save).and_return(false)
        post :create, {:wookie => {}}, valid_session
        assigns(:wookie).should be_a_new(Wookie)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wookie.any_instance.stub(:save).and_return(false)
        post :create, {:wookie => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wookie" do
        wookie = Wookie.create! valid_attributes
        # Assuming there are no other wookies in the database, this
        # specifies that the Wookie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Wookie.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => wookie.to_param, :wookie => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested wookie as @wookie" do
        wookie = Wookie.create! valid_attributes
        put :update, {:id => wookie.to_param, :wookie => valid_attributes}, valid_session
        assigns(:wookie).should eq(wookie)
      end

      it "redirects to the wookie" do
        wookie = Wookie.create! valid_attributes
        put :update, {:id => wookie.to_param, :wookie => valid_attributes}, valid_session
        response.should redirect_to(wookie)
      end
    end

    describe "with invalid params" do
      it "assigns the wookie as @wookie" do
        wookie = Wookie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wookie.any_instance.stub(:save).and_return(false)
        put :update, {:id => wookie.to_param, :wookie => {}}, valid_session
        assigns(:wookie).should eq(wookie)
      end

      it "re-renders the 'edit' template" do
        wookie = Wookie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wookie.any_instance.stub(:save).and_return(false)
        put :update, {:id => wookie.to_param, :wookie => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wookie" do
      wookie = Wookie.create! valid_attributes
      expect {
        delete :destroy, {:id => wookie.to_param}, valid_session
      }.to change(Wookie, :count).by(-1)
    end

    it "redirects to the wookies list" do
      wookie = Wookie.create! valid_attributes
      delete :destroy, {:id => wookie.to_param}, valid_session
      response.should redirect_to(wookies_url)
    end
  end

end
